### ISSUE TITLE
Doc Error

### ISSUE THREAD

**Issue by coolyjg** [syswonder/rukos#17]
Doc check in CI fails after Rustc nightly version was updated to `1.75.0-nightly (d627cf07c 2023-10-10)`.
Output message is printed below, and I think it's the same issue as [this](https://github.com/rust-lang/rust/issues/55001)
```
error: internal compiler error: compiler/rustc_hir_analysis/src/collect.rs:889:14: impossible case reached

thread 'rustc' panicked at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/compiler/rustc_errors/src/lib.rs:1656:9:
Box<dyn Any>
stack backtrace:
   0:     0x7f8301bc152c - std::backtrace_rs::backtrace::libunwind::trace::he58e745adb760569
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f8301bc152c - std::backtrace_rs::backtrace::trace_unsynchronized::hcfd8b2703e8799b2
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8301bc152c - std::sys_common::backtrace::_print_fmt::hc1928915cdd9f8ed
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f8301bc152c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf9671ae59df2367d
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f8301c27e10 - core::fmt::rt::Argument::fmt::hb9f080ef462c2f45
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/fmt/rt.rs:142:9
   5:     0x7f8301c27e10 - core::fmt::write::h222ab15e9e49527b
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/fmt/mod.rs:1117:17
   6:     0x7f8301bb487f - std::io::Write::write_fmt::he12c7e4f7bd7b841
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/io/mod.rs:1763:15
   7:     0x7f8301bc1314 - std::sys_common::backtrace::_print::h2deb383506f4e242
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f8301bc1314 - std::sys_common::backtrace::print::hb813b891a443652d
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f8301bc4127 - std::panicking::default_hook::{{closure}}::h693232489aac5fa3
  10:     0x7f8301bc3e6a - std::panicking::default_hook::h046644a8e6cf71ef
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/panicking.rs:292:9
  11:     0x7f8[300](https://github.com/syswonder/rukos/actions/runs/6477899459/job/17588835573?pr=14#step:4:301)d0e9f5 - std[b26b9704b147c2d]::panicking::update_hook::<alloc[eed55dc9fbda562b]::boxed::Box<rustc_driver_impl[2651547ecd42fa48]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f8[301](https://github.com/syswonder/rukos/actions/runs/6477899459/job/17588835573?pr=14#step:4:302)bc48c8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb2346c3bc264[303](https://github.com/syswonder/rukos/actions/runs/6477899459/job/17588835573?pr=14#step:4:304)5
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/alloc/src/boxed.rs:2021:9
  13:     0x7f8301bc48c8 - std::panicking::rust_panic_with_hook::ha6534e6ac616d42e
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/panicking.rs:735:13
  14:     0x7f83010c0f44 - std[b26b9704b147c2d]::panicking::begin_panic::<rustc_errors[eb3fa16f16611621]::ExplicitBug>::{closure#0}
  15:     0x7f83010b7006 - std[b26b9704b147c2d]::sys_common::backtrace::__rust_end_short_backtrace::<std[b26b9704b147c2d]::panicking::begin_panic<rustc_errors[eb3fa16f16611621]::ExplicitBug>::{closure#0}, !>
  16:     0x7f83010b19b6 - std[b26b9704b147c2d]::panicking::begin_panic::<rustc_errors[eb3fa16f16611621]::ExplicitBug>
  17:     0x7f830109a674 - <rustc_errors[eb3fa16f16611621]::HandlerInner>::bug::<alloc[eed55dc9fbda562b]::string::String>
  18:     0x7f830109a434 - <rustc_errors[eb3fa16f16611621]::Handler>::bug::<alloc[eed55dc9fbda562b]::string::String>
  19:     0x7f830113bcfd - rustc_middle[32ae946643ac3c85]::util::bug::opt_span_bug_fmt::<rustc_span[2258fd5a24697d4]::span_encoding::Span>::{closure#0}
  20:     0x7f8301122c5a - rustc_middle[32ae946643ac3c85]::ty::context::tls::with_opt::<rustc_middle[32ae946643ac3c85]::util::bug::opt_span_bug_fmt<rustc_span[2258fd5a24697d4]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f8301122b38 - rustc_middle[32ae946643ac3c85]::ty::context::tls::with_context_opt::<rustc_middle[32ae946643ac3c85]::ty::context::tls::with_opt<rustc_middle[32ae946643ac3c85]::util::bug::opt_span_bug_fmt<rustc_span[2258fd5a24697d4]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f82ff14d7c0 - rustc_middle[32ae946643ac3c85]::util::bug::bug_fmt
  23:     0x7f83003a5c1b - rustc_hir_analysis[1de63d7b804d7227]::collect::adt_def
  24:     0x7f82ff03a1c3 - rustc_query_impl[aa7cda36b1573e15]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[aa7cda36b1573e15]::query_impl::adt_def::dynamic_query::{closure#2}::{closure#0}, rustc_middle[32ae946643ac3c85]::query::erase::Erased<[u8; 8usize]>>
  25:     0x7f82ff3d49d1 - rustc_query_system[a4e9c8652a0c2e4c]::query::plumbing::try_execute_query::<rustc_query_impl[aa7cda36b1573e15]::DynamicConfig<rustc_query_system[a4e9c8652a0c2e4c]::query::caches::DefaultCache<rustc_span[2258fd5a24697d4]::def_id::DefId, rustc_middle[32ae946643ac3c85]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[aa7cda36b1573e15]::plumbing::QueryCtxt, false>
  26:     0x7f83007d3572 - rustc_query_impl[aa7cda36b1573e15]::query_impl::adt_def::get_query_non_incr::__rust_end_short_backtrace
  27:     0x560ffeddfe8c - rustc_middle[32ae946643ac3c85]::query::plumbing::query_get_at::<rustc_query_system[a4e9c8652a0c2e4c]::query::caches::DefaultCache<rustc_span[2258fd5a24697d4]::def_id::DefId, rustc_middle[32ae946643ac3c85]::query::erase::Erased<[u8; 8usize]>>>
  28:     0x560ffef6e53b - rustdoc[d8cbe265f408053b]::html::render::print_item::display_c_like_variant
  29:     0x560ffef6f53a - rustdoc[d8cbe265f408053b]::html::render::print_item::render_enum_fields
  30:     0x560ffef652dd - rustdoc[d8cbe265f408053b]::html::render::print_item::print_item
  31:     0x560ffef4acf3 - <rustdoc[d8cbe265f408053b]::html::render::context::Context>::render_item
  32:     0x560ffef5b960 - <rustdoc[d8cbe265f408053b]::html::render::context::Context as rustdoc[d8cbe265f408053b]::formats::renderer::FormatRenderer>::item
  33:     0x560ffeff51c6 - rustdoc[d8cbe265f408053b]::main_args::{closure#1}::{closure#0}::{closure#0}
  34:     0x560ffedef455 - std[b26b9704b147c2d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ae17b0dc96344795]::util::run_in_thread_with_globals<rustc_interface[ae17b0dc96344795]::interface::run_compiler<core[49a1b4ca451b5b93]::result::Result<(), rustc_span[2258fd5a24697d4]::ErrorGuaranteed>, rustdoc[d8cbe265f408053b]::main_args::{closure#1}>::{closure#0}, core[49a1b4ca451b5b93]::result::Result<(), rustc_span[2258fd5a24697d4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[49a1b4ca451b5b93]::result::Result<(), rustc_span[2258fd5a24697d4]::ErrorGuaranteed>>
  35:     0x560ffee22d0e - <<std[b26b9704b147c2d]::thread::Builder>::spawn_unchecked_<rustc_interface[ae17b0dc96344795]::util::run_in_thread_with_globals<rustc_interface[ae17b0dc96344795]::interface::run_compiler<core[49a1b4ca451b5b93]::result::Result<(), rustc_span[2258fd5a24697d4]::ErrorGuaranteed>, rustdoc[d8cbe265f408053b]::main_args::{closure#1}>::{closure#0}, core[49a1b4ca451b5b93]::result::Result<(), rustc_span[2258fd5a24697d4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[49a1b4ca451b5b93]::result::Result<(), rustc_span[2258fd5a24697d4]::ErrorGuaranteed>>::{closure#1} as core[49a1b4ca451b5b93]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  36:     0x7f8301bcf835 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1414df2002a63d1b
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/alloc/src/boxed.rs:2007:9
  37:     0x7f8301bcf835 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h763b81210c017496
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/alloc/src/boxed.rs:2007:9
  38:     0x7f8301bcf835 - std::sys::unix::thread::Thread::new::thread_start::h7411b[328](https://github.com/syswonder/rukos/actions/runs/6477899459/job/17588835573?pr=14#step:4:329)d0362935
                               at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/sys/unix/thread.rs:108:17
  39:     0x7f82fde94b43 - <unknown>
  40:     0x7f82fdf26a00 - <unknown>
  41:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: please attach the file at `/home/runner/work/rukos/rukos/rustc-ice-2023-10-11T04:17:45.472565223Z-3871.txt` to your bug report

note: compiler flags: --crate-type lib -Z unstable-options

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [adt_def] computing ADT definition for `VfsError`
end of query stack
error: could not document `axfs_vfs`
```

**Comment by coolyjg** [comment]
@AuYang261

**Comment by AuYang261** [comment]
I lock the version of rustc to nightly-2023-09-01 and pass the Doc check in CI.
#18
